### ISSUE TITLE
wasm: call `emscripten_set_main_loop`

### ISSUE THREAD

**Issue by dfirebaugh** [HackRVA/badge2023#19]
It seems that the wasm build is missing the call to `emscripten_set_main_loop` 

reference:
https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_set_main_loop
https://emscripten.org/docs/porting/emscripten-runtime-environment.html#emscripten-runtime-environment

a simple example (using SDL): https://github.com/dfirebaugh/spritely/blob/main/src/main.c#L19-L33

I tried to get this working with a change like the following.  However, it doesn't seem to work.  
```diff
--- a/source/hal/init_sdl_sim.c
+++ b/source/hal/init_sdl_sim.c
@@ -95,10 +95,21 @@ static void process_options(int argc, char **argv)
        }
 }

+static int (*main_loop_func)(int, char **) = NULL;
+#ifdef __EMSCRIPTEN__
+#include <emscripten.h>
+void emscripten_main_loop_callback(void *arg) {
+  if (main_loop_func) {
+    main_loop_func(sim_argc, sim_argv);
+  }
+}
+#endif
+
 int hal_run_main(int (*main_func)(int, char**), int argc, char** argv) {

     sim_argc = argc;
     sim_argv = argv;
+               main_loop_func = main_func;

     pthread_t app_thread;
     pthread_create(&app_thread, NULL, main_in_thread, main_func);
@@ -107,6 +118,9 @@ int hal_run_main(int (*main_func)(int, char**), int argc, char** argv) {
     audio_init();
     hal_start_sdl(&argc, &argv);

+#ifdef __EMSCRIPTEN__
+  emscripten_set_main_loop_arg(emscripten_main_loop_callback, NULL, -1, 0);
+#endif
     return 0;
 }
```

> side note emsdk includes a little web server for testing if you are running `source emsdk_env.sh`  -- `emrun --port 8080 source/badge2023_c.html`

Also, I'm not sure how much we actually care about this.

**Comment by smcameron** [comment]
I don't think we care much about it.  I thought it might be easy to get it working, so I gave it a shot, but it wasn't as easy as I was hoping and I didn't succeed.
